# Generated by Django 3.2.14 on 2022-07-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('brand', models.CharField(default='whatever', max_length=32)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
